### ISSUE TITLE
multiple definition of 'yylloc'

### ISSUE THREAD

**Issue by vervaekejonathan** [varigit/uboot-imx#10]
> build machine: ubuntu 21.04
> build command: sudo MACHINE=imx8qm-var-som ./var_make_debian.sh -c bootloader

> debian_imx8qm-var-som$  sudo MACHINE=imx8qm-var-som ./var_make_debian.sh -c bootloader
> =============== Build summary ===============
> Building Debian buster for imx8qm-var-som
> U-Boot config:      imx8qm_var_som_defconfig
> Kernel config:      imx8_var_defconfig
> Default kernel dtb: fsl-imx8qm-var-som-lvds.dtb
> kernel dtbs:        freescale/fsl-imx8qm-var-som-dp.dtb
> 	freescale/fsl-imx8qm-var-som-hdmi.dtb
> 	freescale/fsl-imx8qm-var-som-lvds.dtb
> 	freescale/fsl-imx8qm-var-spear-dp.dtb
> 	freescale/fsl-imx8qm-var-spear-hdmi.dtb
> 	freescale/fsl-imx8qm-var-spear-lvds.dtb
> =============================================
> 
> I: Command: "bootloader" start...
> I: Make U-Boot: imx8qm_var_som_defconfig
> make: Entering directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'
>   CLEAN   scripts/basic
>   CLEAN   scripts/kconfig
>   CLEAN   scripts/dtc
>   CLEAN   spl/u-boot.cfg
>   CLEAN   u-boot.cfg u-boot.lds
>   CLEAN   include/config include/generated spl
>   CLEAN   .config include/autoconf.mk include/autoconf.mk.dep include/config.h
> make: Leaving directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'
> make: Entering directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'
>   HOSTCC  scripts/basic/fixdep
>   HOSTCC  scripts/kconfig/conf.o
>   SHIPPED scripts/kconfig/zconf.tab.c
>   SHIPPED scripts/kconfig/zconf.lex.c
>   SHIPPED scripts/kconfig/zconf.hash.c
>   HOSTCC  scripts/kconfig/zconf.tab.o
>   HOSTLD  scripts/kconfig/conf
> #
> # configuration written to .config
> #
> make: Leaving directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'
> make: Entering directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'
> scripts/kconfig/conf  --silentoldconfig Kconfig
>   CHK     include/config.h
>   UPD     include/config.h
>   CFG     u-boot.cfg
>   GEN     include/autoconf.mk.dep
>   CFG     spl/u-boot.cfg
>   GEN     include/autoconf.mk
>   GEN     spl/include/autoconf.mk
>   CHK     include/config/uboot.release
>   CHK     include/generated/timestamp_autogenerated.h
>   UPD     include/generated/timestamp_autogenerated.h
>   HOSTCC  scripts/dtc/dtc.o
>   HOSTCC  scripts/dtc/flattree.o
>   HOSTCC  scripts/dtc/fstree.o
>   CHK     include/config.h
>   CFG     u-boot.cfg
>   HOSTCC  scripts/dtc/data.o
>   HOSTCC  scripts/dtc/livetree.o
>   HOSTCC  scripts/dtc/treesource.o
>   HOSTCC  scripts/dtc/srcpos.o
>   UPD     include/config/uboot.release
>   HOSTCC  scripts/dtc/checks.o
>   CHK     include/generated/version_autogenerated.h
>   UPD     include/generated/version_autogenerated.h
>   HOSTCC  scripts/dtc/util.o
>   SHIPPED scripts/dtc/dtc-lexer.lex.c
>   SHIPPED scripts/dtc/dtc-parser.tab.h
>   SHIPPED scripts/dtc/dtc-parser.tab.c
>   CC      lib/asm-offsets.s
>   CC      arch/arm/lib/asm-offsets.s
>   HOSTCC  scripts/dtc/dtc-lexer.lex.o
>   CHK     include/generated/generic-asm-offsets.h
>   UPD     include/generated/generic-asm-offsets.h
>   CHK     include/generated/asm-offsets.h
>   UPD     include/generated/asm-offsets.h
>   HOSTCC  scripts/dtc/dtc-parser.tab.o
>   LDS     u-boot.lds
>   HOSTLD  scripts/dtc/dtc
> /usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status
> make[2]: *** [scripts/Makefile.host:108: scripts/dtc/dtc] Error 1
> make[1]: *** [scripts/Makefile.build:425: scripts/dtc] Error 2
> make: *** [Makefile:491: scripts] Error 2
> make: Leaving directory '/home/jonathan/debian_imx8qm-var-som/src/uboot'

**Comment by hj2006** [comment]
@vervaekejonathan , we don't officially support Ubuntu 21.04 LTS, as gcc host for the dtc compiler is different, it is likely to fail.
See https://lkml.org/lkml/2020/4/1/1206 which is also applicable to U-boot dtc. 

Variscite customer portal is our official place for technical questions and you will get faster answers there.
https://varisciteportal.axosoft.com/

Please log your ticket to have the issue tracked and it is best approach to get faster answers. 

Thanks,
-Harshesh

**Comment by eranmati** [comment]
@vervaekejonathan, please follow the instructions on [https://variwiki.com](https://variwiki.com) for the relevant SW release you are trying to build.
For each release we mention the tested host OS versions.

Regards,
Eran

**Comment by vervaekejonathan** [comment]
With the supported OS indeed it compiles flawless.
I think this issue is related to the latest default GCC update in ubuntu 20.10 and 21.04, because 2 weeks ago it worked on 20.10

**Comment by tbitcs** [comment]
Per @hj2006, the issue is as described in LKML. Since this issue was introduced in gcc-10, a simple fix is to simply install gcc-9 and give it priority. 

I verified this allows the Variscite scripts to work in Debian Bullseye (11.2.0). In theory the scripts should also work in Ubuntu 21.04. 

```
apt install gcc-9 g++-9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
```

**Comment by DarthBo** [comment]
@vervaekejonathan you can safely drop the redefinition, it's a oneliner patch, upstream did the same:

https://github.com/u-boot/u-boot/commit/018921ee79d3f30893614b3b2b63b588d8544f73

**Comment by eranmati** [comment]
By the way, see the following general solution for such issues - a guide for building our SW releases using Docker:
https://www.variscite.com/blog/building-variscite-yocto-android-and-debian-images-using-docker/
